runtime: go116

main: ./cmd/app

handlers:
- url: /2020/?
  secure: always
  redirect_http_response_code: 301
  static_files: public/2020/index.html
  upload: public/2020/index.html

- url: /2020/css
  static_dir: public/2020/css

- url: /2020/js
  static_dir: public/2020/js

- url: /2020/images
  static_dir: public/2020/images

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

env_variables:
  HOST: syum.ai
