runtime: go111

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  static_files: public/index.html
  upload: public/index.html

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
