runtime: go111

handlers:
# - url: /
#   static_files: index.html
#   upload: index.html
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

